### PR TITLE
Update The Legend of Zelda Tears of the Kingdom to version 1.1.1

### PR DESCRIPTION
**Pull request by Sildurs-shaders**
Game was updated to version 1.1.1, converted and updated all cheats accordingly.
FSR and quality reduction might only have an effect on emulators, I'm not sure if these should still be included.

EDIT:  I made a bunch of additional changes, it got a bit messy but I hope everything is still clear.
Removed the old fsr and quality reduction code since I believe it only works on emulators, yuzu mainly.
Replaced 1792x1008 with a 1080p one instead, AO is still working just fine with it. 
Added a new cheat for FSR and one for disabling FXAA.
Updated credits and such accordingly.

### CODE REVIEW

**Comment by ChanseyIsTheBest** [comment]
Are any mods included here private leaked ones by theboy181.
 I don't keep track of this stuff that well but I don't want them to be included in the database.

**Comment by Sildurs-shaders** [comment]
Yeah it's quite the mess, especially with emulator specific fixes. I only referred to theboy181 because OldManKain credited him in his 1080p, FXAA and FSR mod, although in an earlier version he mentioned PatchAnon and ChucksFeedAndSeed, which is why I simply credited all of them lol. I doubt anything leaked is included here.

**Comment by CosmicCurator** [comment]
So are these tested on real hardware or not? It's unclear from your comments.

Also don't delete cheats for older versions, we keep them in the db: https://github.com/ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats/pull/28/files#diff-87fefab700cb403fc476366501357781a8805ff8e82c1a9a129f916d2c8b146d

**Comment by Sildurs-shaders** [comment]
Oh you're right I forgot to mention that everything but fxaa, fsr and 1080p has been tested on real hardware, sorry about that. I haven't been able to confirm those on real hardware and it might take me awhile to do so, lend my switch to a family member before the v1.1.1 patch dropped. The rest has been updated to support said game patch and should obviously continue to work just fine. Although I have heard of issues with the shadows one. So if you want to be on the save side only all the resolutions by bad1dea and fps codes by somerandompeople should be included.

**Comment by CosmicCurator** [comment]
We don't need to be too strict in curating cheats, if something is buggy then it's no big deal - there's going to be several more updates incoming for this game anyway. It just wasn't clear whether these as a whole were tested on real hardware or emulator.

You or anyone else can feel free to submit the other cheats when they've been tested anyway. Thanks.

**Pull request merged**
